export const Login_Success = "LOGIN_SUCCESS";
export const Logout = "LOGOUT"
export const Auth_detail = "AUTH_DETAIL";
export const Change_Login_Value = "CHANGE_LOGIN_VALUE";
export const Sign_Success = "SIGN_SUCCESS";
export const Change_SignUp_Value = "CHANGE_SIGNUP_VALUE";
export const Change_Case_Value = "CHANGE_CASE_VALUE";
export const Post_Success = "LOGIN_SUCCESS";
export const All_Cases = "ALL_CASES";
export const Case_Pagination = "PAGINATE_CASE"
export const Get_Cases = "GET_CASES";
export const Get_Profile = "GET_PROFILE";
export const Client_By_Id_Detail = "CLIENT_BY_ID_DETAIL";
export const Specific_Case_Pagination = "SPECIFIC_CASE_PAGINATION";
export const All_Specific_Cases = "ALL_SPECIFIC_CASES";
export const Pending_Case_Pagination = "PENDING_CASE_PAGINATION";
export const All_Pending_Case ="ALL_PENDING_CASE";
export const Ongoing_Case = "ONGOIN_CASE";
export const Ongoing_Case_Pagination = "ONGOING_CASE_PAGINATION";
export const Clear_Cases = "CLEAR_CASES";
export const Get_PracticeArea ="GET_PRACTICE_AREA"
export const Change_Active_Bar = 'CHANGE_ACTIVE_BAR';
export const Change_NavBar = 'CHANGE_NAVBAR';
export const SearchedLawyer = 'SEARCH_LAWYER';